include(_default.m4)
include(netbsd/install-on-hard-disk)
ifelse(INSTALL, full,    [[-include(netbsd/install-full.m4)-]])
ifelse(INSTALL, wx11,    [[-include(netbsd/install-without-x11.m4)-]])
ifelse(INSTALL, minimal, [[-include(netbsd/install-minimal.m4)-]])
ifelse(INSTALL, custom,  [[-include(netbsd/install-custom.m4)-]])
include(netbsd/install-from-http.m4)
ifelse(TIMEZONE, UTC, include(netbsd/timezone.m4))
include(netbsd/root-password.m4)
include(netbsd/root-shell.m4)
include(netbsd/add-user.m4)
ifelse(ENABLE_SSHD, yes, include(netbsd/enable-sshd.m4))
ifelse(ENABLE_NTPD, yes, include(netbsd/enable-ntpd.m4))
ifelse(ENABLE_CGD, yes, include(netbsd/enable-cgd.m4))
ifelse(ENABLE_LVM, yes, include(netbsd/enable-lvm.m4))
ifelse(ENABLE_NTPDATE, yes, include(netbsd/enable-ntpdate.m4))
ifelse(ENABLE_RAIDFRAME, yes, include(netbsd/enable-raidframe.m4))
ifelse(ENABLE_XDM, yes, include(netbsd/enable-xdm.m4))
include(netbsd/reboot.m4)
