{
  "variables": {
    "repository": "ftp.fr.netbsd.org",
    "release": "9.0",
    "arch": "amd64",
    "checksum": "dea2f08778af0ab67e3a89cf01d0e34e0e60eade84288bd21d247632c414cbd934eef22f340d473b55f9603cdd829995d9d7db30acd8af881dad36cf970d2e94",
    "checksum_type": "sha512",
    "root_password": "vagrant",
    "user_password": "vagrant"
  },
  "builders": [{
    "type": "qemu",
    "iso_url": "http://{{user `repository`}}/pub/NetBSD/NetBSD-{{user `release`}}/{{user `arch`}}/installation/cdrom/boot.iso",
    "iso_checksum": "{{user `checksum`}}",
    "iso_checksum_type": "{{user `checksum_type`}}",
    "output_directory": "netbsd-qemu",
    "disk_size": "5000M",
    "format": "qcow2",
    "accelerator": "kvm",
    "vm_name": "netbsd-{{user `release`}}",
    "net_device": "virtio-net",
    "disk_interface": "virtio",
    "ssh_username": "vagrant",
    "ssh_password": "{{user `user_password`}}",
    "boot_wait": "1m",
    "boot_command": [
      "a<enter><wait5s>",
      "a<enter><wait5s>",
      "a<enter><wait5s>",
      "b<enter><wait5s>",
      "a<enter><wait5s>",
      "a<enter><wait5s>",
      "a<enter><wait5s>",
      "b<enter><wait5s>",
      "x<enter><wait5s>",

	"b<enter><wait20s>",
		"a<enter><wait5s>",
		"a<enter><wait5s>",
		"b<enter><wait5s>",

	"i<enter><wait5s>",
		"a<enter><wait5s>",

	"j<enter><wait5s>",
		"a<enter><wait5s>",
		"<enter><wait5s>",
		"b<enter><wait10>",
		"{{user `hostname`}}<enter><wait5s>",
		"{{user `domain`}}<enter><wait5s>",
		"10.0.2.15<enter><wait5s>",
		"0xffffff00<enter><wait5s>",
		"10.0.2.2<enter><wait5s>",
		"e<enter><wait5s>",
		"10.0.2.3<enter><wait5s>"
		"a<enter><wait5s>",

      "x<enter><wait10m>",
      "a<enter><wait5s>",
      "<enter><wait5s>",
      "d<enter><wait5s>",
      "a<enter><wait5s>",
      "{{user `root_password`}}<enter><wait5s>",
      "{{user `root_password`}}<enter><wait5s>",
      "{{user `root_password`}}<enter><wait5s>",
      "g<enter><wait5s>",
      "o<enter><wait5s>",
      "vagrant<enter><wait5s>",
      "a<enter><wait5s>",
      "a<enter><wait5s>",
      "{{user `user_password`}}<enter><wait5s>",
      "{{user `user_password`}}<enter><wait5s>",
      "{{user `user_password`}}<enter><wait5s>",
      "x<enter><wait5s>",
      "<enter><wait5s>",
      "d<enter><wait5s>"]}
  ],
  "provisioners": [
     { "type": "shell",
       "inline": ["uname -a"] }
  ],
  "post-processors": ["vagrant"]
}
