"g<enter><wait5s>",
"o<enter><wait5s>",
"{{user `user_name`}}<enter><wait5s>",
"a<enter><wait5s>",
"a<enter><wait5s>",
"{{user `user_password`}}<enter><wait5s>",
"{{user `user_password`}}<enter><wait5s>",
"{{user `user_password`}}<enter><wait5s>",
