"o<enter><wait5s>",
"{{user `username`}}<enter><wait5s>",
"a<enter><wait5s>",
"a<enter><wait5s>",
"{{user `user_password`}}<enter><wait5s>",
"{{user `user_password`}}<enter><wait5s>",
"{{user `user_password`}}<enter><wait5s>",
