"a<enter><wait5s>",
"a<enter><wait5s>",
"{{user `network_type`}}<enter><wait5s>",
"b<enter><wait5s>",
"{{user `hostname`}}<enter><wait5s>",
"{{user `domain`}}<enter><wait5s>",
"{{user `ipv4`}}<enter><wait5s>",
"{{user `netmask`}}<enter><wait5s>",
"{{user `gateway`}}<enter><wait5s>",
"e<enter><wait5s>",
"{{user `dns`}}<enter><wait5s>",
"a<enter><wait5s>",
